# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-24 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_processingresult_topics_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='directed',
            field=models.BooleanField(default=True),
        ),
    ]
