# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-01 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_graph_directed'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingresult',
            name='cluster_mat',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='processingresult',
            name='topics_mat',
            field=models.TextField(blank=True, default=''),
        ),
    ]
