# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-01 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170301_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processingresult',
            old_name='cluster_mat',
            new_name='clusters_mat',
        ),
    ]
