# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-15 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_processingresult_crit'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingresult',
            name='topics_per_edges_mat',
            field=models.TextField(blank=True, default=''),
        ),
    ]
