# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-16 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_processingresult_topics_per_edges_mat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingresult',
            name='crit',
            field=models.FloatField(null=True),
        ),
    ]
