# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-16 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170316_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingresult',
            name='crit',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
