# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-21 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20170316_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingresult',
            name='pi_mat',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='processingresult',
            name='rho',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='processingresult',
            name='theta_qr_mat',
            field=models.TextField(blank=True, default=''),
        ),
    ]
