# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-21 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20170321_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processingresult',
            old_name='rho',
            new_name='rho_mat',
        ),
    ]
