# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-22 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_processingresult_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processingresult',
            name='log',
        ),
        migrations.RemoveField(
            model_name='processingresult',
            name='param_clusters',
        ),
        migrations.RemoveField(
            model_name='processingresult',
            name='param_topics',
        ),
        migrations.RemoveField(
            model_name='processingresult',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='processingresult',
            name='time',
        ),
        migrations.AddField(
            model_name='graph',
            name='job_log',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='graph',
            name='job_param_clusters',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='graph',
            name='job_param_clusters_max',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='graph',
            name='job_param_topics',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='graph',
            name='job_param_topics_max',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='graph',
            name='job_progress',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='graph',
            name='job_time',
            field=models.FloatField(default=0),
        ),
    ]
