# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-22 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20170322_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingresult',
            name='param_clusters',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='processingresult',
            name='param_topics',
            field=models.IntegerField(default=3),
        ),
    ]
