# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-03 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20170324_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='cluster_to_cluster_cutoff',
            field=models.FloatField(default=0.005),
        ),
    ]
