# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-14 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20170412_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='job_error_log',
            field=models.TextField(blank=True, default=''),
        ),
    ]
