# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-14 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_graph_job_error_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='magic_too_big_to_display_X',
            field=models.BooleanField(default=False),
        ),
    ]
