# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-28 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_graph_magic_too_big_to_display_x'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingresult',
            name='clusters_labels',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='graph',
            name='job_param_clusters_max',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='graph',
            name='job_param_topics_max',
            field=models.IntegerField(default=10),
        ),
    ]
