# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-03 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20170428_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processingresult',
            name='clusters_labels',
        ),
        migrations.AddField(
            model_name='processingresult',
            name='nodes_meta',
            field=models.TextField(blank=True, default=''),
        ),
    ]
