# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-11 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20170503_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='job_param_clusters_max',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='graph',
            name='job_param_topics_max',
            field=models.IntegerField(default=5),
        ),
    ]
