# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-11 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20170511_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
