# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-11 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_graph_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
