# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-16 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20170511_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='original_csv',
            field=models.TextField(blank=True, default=''),
        ),
    ]
