# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-02 12:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='published_on',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2017, 6, 2, 12, 52, 34, 692017, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
